### ISSUE TITLE
ライセンス条件はどうなるのでしょうか？

### ISSUE THREAD

**Issue by mganeko** [gh640/nextjs-blog-example-ja#48]
公開ありがとうございます。
こちらのサンプルを利用させていただきたいと考えています。
ライセンス条件はどうなっているでしょうか？

**Comment by gh640** [comment]
@mganeko 

ご質問くださりありがとうございます。

ご自由にご利用いただいてかまいません。後ほど MIT のライセンスファイル追加しておきます。

**Comment by mganeko** [comment]
回答ありがとうございます。MITラインセンスということで了解しました。
利用させていただきます
